[project]
name = "ComfyUI-Block-Space-V1.0.1"
version = "1.0.1"
description = "A Figma-style layout and snapping engine for the ComfyUI canvas."
license = "MIT"
repository = "https://github.com/tywoodev/ComfyUI-Block-Space"

[publisher]
name = "t-dub"

[tool.comfy]
PublisherId = "t-dub" 
DisplayName = "ComfyUI-Block-Space"
Icon = "https://github.com/tywoodev/ComfyUI-Block-Space/blob/main/assets/logo.svg"